name: "CI workflow"

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: "CI tests"
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Install dependencies and classifier package
      run: make install
    
    - name: Test package
      run: make test

    - name: Train minimal model
      run: make train


  deploy:
    name: "Deploy on GKE"
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Configure docker auth
      run: gcloud auth configure-docker

    - name: Build docker image
      run: docker build -t classifier_web

    - name: Upload image on Google Artifact Registry
      run: |
        docker tag classifier_web us-central1-docker.pkg.dev/data-lake-test-gcp-iac/classifier-web-app/latest
        docker push us-central1-docker.pkg.dev/data-lake-test-gcp-iac/classifier-web-app/latest

    - name: Deploy docker image 
      run: |
        gcloud container clusters create classifier-web-app-cluster \
        --project=data-lake-test-gcp-iac \
        --zone=us-central1 