name: "CI workflow"

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: "CI tests"
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies and classifier package
      run: make install
    
    - name: Test package
      run: make test

    - name: Train minimal model
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: make train
      